name: validate_alerts
on:
  pull_request:
    paths-ignore:
      - 'log_alerts/**'
      - 'trigmetry2.0-alert-configs/**'
jobs:
  build:
    name : validate_alerts
    runs-on: ubuntu-latest
    steps:
      - name: "No Build Required"
        run: |
          echo "No Build Required"